inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.2

# Keep diffs clean
Layout/TrailingBlankLines:
  EnforcedStyle: final_blank_line

# RSpec uses unparenthesized blocks all over; allow the idiomatic RSpec style.
Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

# No way to avoid large blocks in RSpec
Metrics/BlockLength:
  Exclude:
    - spec/**/*

# Allow the gem to have a non-snakecase name
Naming/FileName:
  Exclude:
    - 'lib/onfleet-ruby.rb'

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Exclude:
    - spec/**/*

